// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _4._07._23_2_.Models;

#nullable disable

namespace _4._07._23_2_.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230731100013_mig_1")]
    partial class mig_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_4._07._23_2_.Models.CalismaTuru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("calismaTuru");
                });

            modelBuilder.Entity("_4._07._23_2_.Models.Deneyim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("deneyims");
                });

            modelBuilder.Entity("_4._07._23_2_.Models.Firma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IsSahibiId")
                        .HasColumnType("int");

                    b.Property<string>("aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("kurulusYili")
                        .HasColumnType("int");

                    b.Property<string>("mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("telno")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IsSahibiId");

                    b.ToTable("firmas");
                });

            modelBuilder.Entity("_4._07._23_2_.Models.FirmaSektor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FirmaId")
                        .HasColumnType("int");

                    b.Property<int?>("SektorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId");

                    b.HasIndex("SektorId");

                    b.ToTable("firmaSektors");
                });

            modelBuilder.Entity("_4._07._23_2_.Models.Ilan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CalismaTuruId")
                        .HasColumnType("int");

                    b.Property<int>("DeneyimId")
                        .HasColumnType("int");

                    b.Property<int>("FirmaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GetDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("egitimseviyesi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firmaWebSite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("maaş")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CalismaTuruId");

                    b.HasIndex("DeneyimId");

                    b.HasIndex("FirmaId");

                    b.ToTable("Ilans");
                });

            modelBuilder.Entity("_4._07._23_2_.Models.IsBakanIlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IlanId")
                        .HasColumnType("int");

                    b.Property<int>("JobSeekerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IlanId");

                    b.HasIndex("JobSeekerId");

                    b.ToTable("ısBakanIlans");
                });

            modelBuilder.Entity("_4._07._23_2_.Models.IsBakanMeslek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("JobSeekerId")
                        .HasColumnType("int");

                    b.Property<int>("MeslekId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobSeekerId");

                    b.HasIndex("MeslekId");

                    b.ToTable("ısBakanMesleks");
                });

            modelBuilder.Entity("_4._07._23_2_.Models.IsSahibi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KullanıcıSifresi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("soyisim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("telno")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.ToTable("isSahibis");
                });

            modelBuilder.Entity("_4._07._23_2_.Models.JobSeeker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KullanıcıSifresi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cinsiyet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dogumtarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("egitimSeviyesi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ilce")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sehir")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("soyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("telno")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.ToTable("Seekers");
                });

            modelBuilder.Entity("_4._07._23_2_.Models.Meslek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("mesleks");
                });

            modelBuilder.Entity("_4._07._23_2_.Models.Sektor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("sektors");
                });

            modelBuilder.Entity("_4._07._23_2_.Models.Firma", b =>
                {
                    b.HasOne("_4._07._23_2_.Models.IsSahibi", "IsSahibi")
                        .WithMany()
                        .HasForeignKey("IsSahibiId");

                    b.Navigation("IsSahibi");
                });

            modelBuilder.Entity("_4._07._23_2_.Models.FirmaSektor", b =>
                {
                    b.HasOne("_4._07._23_2_.Models.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_4._07._23_2_.Models.Sektor", "Sektor")
                        .WithMany()
                        .HasForeignKey("SektorId");

                    b.Navigation("Firma");

                    b.Navigation("Sektor");
                });

            modelBuilder.Entity("_4._07._23_2_.Models.Ilan", b =>
                {
                    b.HasOne("_4._07._23_2_.Models.CalismaTuru", "CalismaTuru")
                        .WithMany()
                        .HasForeignKey("CalismaTuruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_4._07._23_2_.Models.Deneyim", "Deneyim")
                        .WithMany()
                        .HasForeignKey("DeneyimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_4._07._23_2_.Models.Firma", "Firma")
                        .WithMany()
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalismaTuru");

                    b.Navigation("Deneyim");

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("_4._07._23_2_.Models.IsBakanIlan", b =>
                {
                    b.HasOne("_4._07._23_2_.Models.Ilan", "Ilan")
                        .WithMany()
                        .HasForeignKey("IlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_4._07._23_2_.Models.JobSeeker", "JobSeeker")
                        .WithMany()
                        .HasForeignKey("JobSeekerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ilan");

                    b.Navigation("JobSeeker");
                });

            modelBuilder.Entity("_4._07._23_2_.Models.IsBakanMeslek", b =>
                {
                    b.HasOne("_4._07._23_2_.Models.JobSeeker", "JobSeeker")
                        .WithMany()
                        .HasForeignKey("JobSeekerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_4._07._23_2_.Models.Meslek", "Meslek")
                        .WithMany()
                        .HasForeignKey("MeslekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobSeeker");

                    b.Navigation("Meslek");
                });
#pragma warning restore 612, 618
        }
    }
}
